/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mangruf;

import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author Oluwatobi
 */
public class Sender extends javax.swing.JFrame {

    /**
     * Creates new form Sender
     */
    private ConfigUtility configUtil = new ConfigUtility();
    private EncryptUtility encryptUtil = new EncryptUtility();
    public Sender() {
        initComponents();
        pack();
        setLocationRelativeTo(null);	// center on screen
        setDefaultCloseOperation(EXIT_ON_CLOSE);	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbTo = new javax.swing.JLabel();
        jTxtTo = new javax.swing.JTextField();
        jLbSubj = new javax.swing.JLabel();
        jTxtSubj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMsg = new javax.swing.JTextArea();
        jBtSend = new javax.swing.JButton();
        jBtEncrypt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemSett = new javax.swing.JMenuItem();
        jMenuDecoder = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encoder");

        jLbTo.setText("To");

        jTxtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtToActionPerformed(evt);
            }
        });

        jLbSubj.setText("Subject");

        jTextAreaMsg.setColumns(20);
        jTextAreaMsg.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMsg);

        jBtSend.setText("SEND");
        jBtSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSendActionPerformed(evt);
            }
        });

        jBtEncrypt.setText("ENCRYPT MESSAGE");
        jBtEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEncryptActionPerformed(evt);
            }
        });

        jMenuFile.setText("File");

        jMenuItemSett.setText("Settings");
        jMenuItemSett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSett);

        jMenuBar1.add(jMenuFile);

        jMenuDecoder.setText("Decoder");
        jMenuDecoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDecoderActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuDecoder);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbTo)
                    .addComponent(jLbSubj))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtTo)
                    .addComponent(jTxtSubj, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jBtSend, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
            .addComponent(jBtEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTo)
                    .addComponent(jTxtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtSend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSubj)
                    .addComponent(jTxtSubj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSendActionPerformed
        // TODO add your handling code here:
        
		if (!validateFields()) {
			return;
		}
		
		String toAddress = jTxtTo.getText();
		String subject = jTxtSubj.getText();
		String message = jTextAreaMsg.getText();
                
		try {
                String enctext = encryptUtil.Encrypt(message);
//                JDialog.setDefaultLookAndFeelDecorated(true);
    int response = JOptionPane.showConfirmDialog(null, "You are about to encrypt and send this message", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
    } else if (response == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, 
                        "Message encrypted. Now sending...",
                        "Done", JOptionPane.INFORMATION_MESSAGE);
                Properties smtpProperties = configUtil.loadProperties();
                EmailUtility.sendEmail(smtpProperties, toAddress, subject, message, null);
			JOptionPane.showMessageDialog(this, 
					"The e-mail has been sent successfully!");
    } else if (response == JOptionPane.CLOSED_OPTION) {
    }
			
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, 
					"Error while sending the e-mail: " + ex.getMessage(),
					"Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_jBtSendActionPerformed

    private void jTxtToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtToActionPerformed

    private void jMenuItemSettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettActionPerformed
        // TODO add your handling code here:
        SettingsDialog sett = new SettingsDialog(Sender.this, true, configUtil);
        sett.setVisible(true);
    }//GEN-LAST:event_jMenuItemSettActionPerformed

    private void jBtEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEncryptActionPerformed
        // TODO add your handling code here:
        try {
            String message = jTextAreaMsg.getText().toString();
            if (message.isEmpty())
            {
                JOptionPane.showMessageDialog(this, 
                                "The mail body cannot be empty",
                                "Error", JOptionPane.ERROR_MESSAGE);
            }else
            {
                encryptUtil.Encrypt(message);
                JOptionPane.showMessageDialog(this, 
                                encryptUtil.Encrypt(message),
                                "Done", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                            "Error while encrypting the e-mail: " + e.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtEncryptActionPerformed

    private void jMenuDecoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDecoderActionPerformed
        // TODO add your handling code here:
        Decoder decoder = new Decoder();
        decoder.setVisible(true);
    }//GEN-LAST:event_jMenuDecoderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sender().setVisible(true);
            }
        });
    }
    
    private boolean validateFields() {
            if (jTxtTo.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, 
                                    "Please enter To address!",
                                    "Error", JOptionPane.ERROR_MESSAGE);
                    jTxtTo.requestFocus();
                    return false;
            }

            if (jTxtSubj.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, 
                                    "Please enter subject!",
                                    "Error", JOptionPane.ERROR_MESSAGE);
                    jTxtSubj.requestFocus();
                    return false;
            }

            if (jTextAreaMsg.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, 
                                    "Please enter message!",
                                    "Error", JOptionPane.ERROR_MESSAGE);
                    jTextAreaMsg.requestFocus();
                    return false;
            }

            return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtEncrypt;
    private javax.swing.JButton jBtSend;
    private javax.swing.JLabel jLbSubj;
    private javax.swing.JLabel jLbTo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDecoder;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemSett;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMsg;
    private javax.swing.JTextField jTxtSubj;
    private javax.swing.JTextField jTxtTo;
    // End of variables declaration//GEN-END:variables
}
